CRUD/apps/course/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.course.views import CourseList, CourseCreate, CourseUpdate, CourseDelete, index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', CourseCreate.as_view(), name='course_create'),
    url(r'^listar', CourseList.as_view(), name='course_list'),
    url(r'^editar/(?P<pk>\d+)/$', CourseUpdate.as_view(), name='course_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', CourseDelete.as_view(), name='course_delete'),
]

CRUD/apps/exam/urls.py
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.exam.views import index, ExamList, ExamCreate, ExamUpdate, ExamDelete \
,ScoreCreate, ScoreUpdate, ScoreList, ScoreDelete 

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', ExamCreate.as_view(), name='exam_create'),
    url(r'^listar', ExamList.as_view(), name='exam_list'),
    url(r'^editar/(?P<pk>\d+)/$', ExamUpdate.as_view(), name='exam_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', ExamDelete.as_view(), name='exam_delete'),
    url(r'^nota/nuevo$', ScoreCreate.as_view(), name='score_create'),
    url(r'^nota/listar', ScoreList.as_view(), name='score_list'),
    url(r'^nota/editar/(?P<pk>\d+)/$', ScoreUpdate.as_view(), name='score_edit'),
    url(r'^nota/eliminar/(?P<pk>\d+)/$', ScoreDelete.as_view(), name='score_delete'),
]

CRUD/apps/student/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.student.views import StudentList, StudentCreate, StudentUpdate, StudentDelete, index, StudentRedAverage, StudentAverage

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', StudentCreate.as_view(), name='student_create'),
    url(r'^listar', StudentList.as_view(), name='student_list'),
    url(r'^editar/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student_delete'),
    url(r'^promedioRojoList', StudentRedAverage, name='student_red_average'),
    url(r'^promedios', StudentAverage, name='student_average'),
]

CRUD/collegeSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.student.urls', namespace="index")),
    url(r'^admin/', admin.site.urls),
    url(r'^curso/', include('apps.course.urls', namespace="course")),
    url(r'^pruebas/', include('apps.exam.urls', namespace="exam")),
    url(r'^alumnos/', include('apps.student.urls', namespace="student")),
]

CRUD/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="/">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Estudiante <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'student:student_create' %}">Registrar</a></li>
				                        	<li><a href="{% url 'student:student_list' %}">Listar</a></li>
				                        	<li><a href="{% url 'student:student_average' %}">Promedios</a></li>
				                        	<li><a href="{% url 'student:student_red_average' %}">Reporte - alumnos con cursos en rojo</a></li>
				                        </ul>
		                      		</li>
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Cursos <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'course:course_create' %}">Registrar</a></li>
				                        	<li><a href="{% url 'course:course_list' %}">Listar</a></li>
				                        </ul>
		                      		</li>
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pruebas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'exam:exam_create' %}">Registrar</a></li>
				                        	<li><a href="{% url 'exam:exam_list' %}">Listar</a></li>
				                        </ul>
		                      		</li>
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Notas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'exam:score_create' %}">Registrar</a></li>
				                        	<li><a href="{% url 'exam:score_list' %}">Listar</a></li>
				                        </ul>
		                      		</li>
			                        
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>