CRUD/apps/exam/urls.py
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.exam.views import index, ExamList, ExamCreate, ExamUpdate, ExamDelete \
,ScoreCreate, ScoreUpdate, ScoreList, ScoreDelete 

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', ExamCreate.as_view(), name='exam_create'),
    url(r'^listar', ExamList.as_view(), name='exam_list'),
    url(r'^editar/(?P<pk>\d+)/$', ExamUpdate.as_view(), name='exam_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', ExamDelete.as_view(), name='exam_delete'),
    url(r'^nota/nuevo$', ScoreCreate.as_view(), name='score_create'),
    url(r'^nota/listar', ScoreList.as_view(), name='score_list'),
    url(r'^nota/editar/(?P<pk>\d+)/$', ScoreUpdate.as_view(), name='score_edit'),
    url(r'^nota/eliminar/(?P<pk>\d+)/$', ScoreDelete.as_view(), name='score_delete'),
]

CRUD/collegeSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.student.urls', namespace="index")),
    url(r'^admin/', admin.site.urls),
    url(r'^curso/', include('apps.course.urls', namespace="course")),
    url(r'^pruebas/', include('apps.exam.urls', namespace="exam")),
    url(r'^alumnos/', include('apps.student.urls', namespace="student")),
]

CRUD/templates/score/index.html
{% extends 'base/base.html' %}

{% block content %}
	<h1>HOME</h1>
{% endblock %}

CRUD/templates/score/score_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar este registro?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'exam:score_list' %}">Cancelar</a>
</form>
{% endblock %}

CRUD/templates/score/score_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-success">Registrar</button>
</form>
{% endblock %}

CRUD/templates/score/score_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>Nombre del Alumno</td>
			<td>Prueba</td>
			<td>Nota</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for score in object_list %}
		<tr>
			<td>{{ score.Student.name }}</td>
			<td>{{ score.Exam.title }}</td>
			<td>{{ score.score }}</td>
			
			<td>
				<a class="btn btn-primary" href="{% url 'exam:score_edit' score.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'exam:score_delete' score.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de notas</h1>
		{% endif %}
	</tbody>
</table> 
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
{% endblock%}