CRUD/apps/exam/urls.py
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.exam.views import index, ExamList, ExamCreate, ExamUpdate, ExamDelete \
,ScoreCreate, ScoreUpdate, ScoreList, ScoreDelete 

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', ExamCreate.as_view(), name='exam_create'),
    url(r'^listar', ExamList.as_view(), name='exam_list'),
    url(r'^editar/(?P<pk>\d+)/$', ExamUpdate.as_view(), name='exam_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', ExamDelete.as_view(), name='exam_delete'),
    url(r'^nota/nuevo$', ScoreCreate.as_view(), name='score_create'),
    url(r'^nota/listar', ScoreList.as_view(), name='score_list'),
    url(r'^nota/editar/(?P<pk>\d+)/$', ScoreUpdate.as_view(), name='score_edit'),
    url(r'^nota/eliminar/(?P<pk>\d+)/$', ScoreDelete.as_view(), name='score_delete'),
]

CRUD/collegeSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.student.urls', namespace="index")),
    url(r'^admin/', admin.site.urls),
    url(r'^curso/', include('apps.course.urls', namespace="course")),
    url(r'^pruebas/', include('apps.exam.urls', namespace="exam")),
    url(r'^alumnos/', include('apps.student.urls', namespace="student")),
]

CRUD/apps/exam/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models
from apps.course.models import Course
from apps.student.models import Student

# Create your models here.

class Exam(models.Model):
	title = models.CharField(max_length=255)
	Course = models.ForeignKey(Course, null=True, blank=True, on_delete=models.CASCADE)

	def __str__(self):
		return '{}'.format(self.title)
	
class Score(models.Model):
	Student = models.ForeignKey(Student, null=True, blank=True, on_delete=models.CASCADE)
	Exam = models.ForeignKey(Exam, null=True, blank=True, on_delete=models.CASCADE)
	score = models.IntegerField()

CRUD/apps/exam/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django import forms

from apps.exam.models import Exam, Score



class ExamForm(forms.ModelForm):

	class Meta:
		model = Exam
		fields = [
			'title',
			'Course'
		]
		labels = {
			'titulo': 'Titulo',
			'cursos': 'Cursos'
		}
		widgets = {
			'title':forms.TextInput(attrs={'class':'form-control'}),
			'Course':forms.Select(attrs={'class':'form-control'}),
		}


class ScoreForm(forms.ModelForm):

	class Meta:
		model = Score
		fields = [
			'score',
			'Exam',
			'Student',
		]
		labels = {
			'nota': 'Nota',
			'prueba': 'Prueba',
			'estudiante': 'Estudiante',			
		}
		widgets = {
			'score':forms.TextInput(attrs={'class':'form-control'}),
			'Exam':forms.Select(attrs={'class':'form-control'}),
			'Student':forms.Select(attrs={'class':'form-control'}),
		}

CRUD/apps/exam/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.exam.forms import ExamForm, ScoreForm
from apps.exam.models import Exam, Score

from apps.course.forms import CourseForm
from apps.course.models import Course

from apps.student.forms import StudentForm
from apps.student.models import Student
# Create your views here.

# Exam Views
def index(request):
	return render(request, 'exam/index.html')


class ExamList(ListView):
	model = Exam
	template_name = 'exam/exam_list.html'
	paginate_by = 10

class ExamCreate(CreateView):
	model = Exam
	template_name = 'exam/exam_form.html'
	form_class = ExamForm
	success_url = reverse_lazy('exam:exam_list')

class ExamUpdate(UpdateView):
	model = Exam
	second_model = Course
	template_name = 'exam/exam_form.html'
	form_class = ExamForm
	second_form_class = CourseForm
	success_url = reverse_lazy('exam:exam_list')


class ExamDelete(DeleteView):
	model = Exam
	template_name = 'exam/exam_delete.html'
	success_url = reverse_lazy('exam:exam_list')


#Score Views

class ScoreList(ListView):
	model = Score
	template_name = 'score/score_list.html'
	paginate_by = 10

class ScoreCreate(CreateView):
	model = Score
	template_name = 'score/score_form.html'
	form_class = ScoreForm
	success_url = reverse_lazy('exam:score_list')

class ScoreUpdate(UpdateView):
	model = Score
	template_name = 'score/score_form.html'
	form_class = ScoreForm
	success_url = reverse_lazy('exam:score_list')

class ScoreDelete(DeleteView):
	model = Score
	template_name = 'score/score_delete.html'
	success_url = reverse_lazy('exam:score_list')

CRUD/templates/exam/exam_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro {{ object.title }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'exam:exam_list' %}">Cancelar</a>
</form>
{% endblock %}

CRUD/templates/exam/exam_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-success">Registrar</button>
</form>
{% endblock %}

CRUD/templates/exam/exam_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Titulo</td>
			<td>Curso</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for exam in object_list %}
		<tr>
			<td>{{ exam.id }}</td>
			<td>{{ exam.title }}</td>
			<td>{{ exam.Course.name }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'exam:exam_edit' exam.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'exam:exam_delete' exam.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay pruebas registradas</h1>
		{% endif %}
	</tbody>
</table> 
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
{% endblock%}

CRUD/templates/exam/index.html
{% extends 'base/base.html' %}

{% block content %}
	<h1>HOME</h1>
{% endblock %}