CRUD/apps/student/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url, include

from apps.student.views import StudentList, StudentCreate, StudentUpdate, StudentDelete, index, StudentRedAverage, StudentAverage

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', StudentCreate.as_view(), name='student_create'),
    url(r'^listar', StudentList.as_view(), name='student_list'),
    url(r'^editar/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student_delete'),
    url(r'^promedioRojoList', StudentRedAverage, name='student_red_average'),
    url(r'^promedios', StudentAverage, name='student_average'),
]

CRUD/collegeSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.student.urls', namespace="index")),
    url(r'^admin/', admin.site.urls),
    url(r'^curso/', include('apps.course.urls', namespace="course")),
    url(r'^pruebas/', include('apps.exam.urls', namespace="exam")),
    url(r'^alumnos/', include('apps.student.urls', namespace="student")),
]

CRUD/apps/student/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from apps.course.models import Course

# Create your models here.

class Student(models.Model):
	name = models.CharField(max_length=100)
	Course = models.ManyToManyField(Course, blank=True)
	
	def __str__(self):
		return '{}'.format(self.name)

CRUD/apps/student/forms.py
from __future__ import unicode_literals, absolute_import
from django import forms
from apps.student.models import Student


class StudentForm(forms.ModelForm):

	class Meta:
		model = Student

		fields = [
			'name',
			'Course',
		]
		labels = {
			'nombre': 'Nombre',
			'cursos': 'Cursos'
		}
		widgets = {
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'Course': forms.CheckboxSelectMultiple(),
		}

CRUD/apps/student/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.student.forms import StudentForm
from apps.student.models import Student

def index(request):
	return render(request, 'student/index.html')

class StudentList(ListView):
	model = Student
	template_name = 'student/student_list.html'
	paginate_by = 10

class StudentCreate(CreateView):
	model = Student
	form_class = StudentForm
	template_name = 'student/student_form.html'
	success_url = reverse_lazy('student:student_list')


class StudentUpdate(UpdateView):
	model = Student
	form_class = StudentForm
	template_name = 'student/student_form.html'
	success_url = reverse_lazy('student:student_list')


class StudentDelete(DeleteView):
	model = Student
	template_name = 'student/student_delete.html'
	success_url = reverse_lazy('student:student_list')

#Listado de alumnos y su promedio
def StudentAverage(request):
	estudents = Student.objects.raw('SELECT est.id, est.name, ROUND(AVG(sc.score),1) AS avg FROM student_student AS est INNER JOIN exam_score AS sc ON est.id = sc.student_id GROUP BY est.id, est.name')
	contexto = {'object_list':estudents}
	return render(request, 'student/student_average.html', contexto)

#Listado de alumnos con mas de un promedio rojo
def StudentRedAverage(request):
	estudents = Student.objects.raw('SELECT savg.id, savg.name FROM ( SELECT est.id, est.name, c.name AS course_name, AVG(sc.score) AS avg FROM student_student AS est INNER JOIN exam_score AS sc ON est.id = sc.Student_id INNER JOIN exam_exam AS ex ON sc.Exam_id = ex.id INNER JOIN course_course AS c ON ex.Course_id = c.id GROUP BY est.id, c.name ) AS savg GROUP BY savg.id HAVING SUM(if(savg.avg<4, 1, 0))>1')
	contexto = {'object_list':estudents}
	return render(request, 'student/student_red_average.html', contexto)

CRUD/templates/student/index.html
{% extends 'base/base.html' %}

{% block content %}
	<h1>HOME</h1>
{% endblock %}

CRUD/templates/student/student_average.html
{% extends 'base/base.html' %}

{% block content %}

	<h4>Promedios de notas</h4>

	<br>

	{% if object_list %}

	<table class="table table-bordered">
		<thead>
			<tr>
				<td>#</td>
				<td>Nombre</td>
				<td>Promedio</td>
			</tr>
			
		</thead>
		<tbody>
			
			{% for student in object_list %}
			<tr>
				<td>{{ student.id }}</td>
				<td>{{ student.name }}</td>
				<td>{{ student.avg }}</td>
			</tr>
			{% endfor %}
			
			
		</tbody>
	</table> 
	<ul class="pager">
		<li>
			{% if page_obj.has_previous %}
	       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
			{% endif %}
	        </li>
		<li>
			{% if page_obj.has_next %}
	     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
	    	{% endif %}
	    </li>
	</ul>
	{% else %}
		<h3>No hay registros de estudiantes</h3>
	{% endif %}

{% endblock%}

CRUD/templates/student/student_delete.html
{% extends 'base/base.html' %}

{% block content %}

<h4> Eliminar Estudiante</h4>

<br>

<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.name }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'student:student_list' %}">Cancelar</a>
</form>
{% endblock %}

CRUD/templates/student/student_form.html
{% extends 'base/base.html' %}

{% block content %}

<h4>Ingresar Estudiante</h4>

<br>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit" class="btn btn-success">Registrar</button>
</form>
{% endblock %}

CRUD/templates/student/student_list.html
{% extends 'base/base.html' %}

{% block content %}

<h4> Estudiantes </h4>

<br>

{% if object_list %}

	<table class="table table-bordered">
		<thead>
			<tr>
				<td>#</td>
				<td>Nombre</td>
				<td>Acciones</td>
			</tr>
			
		</thead>
		<tbody>
			
			{% for student in object_list %}
			<tr>
				<td>{{ student.id }}</td>
				<td>{{ student.name }}</td>
				<td>
					<a class="btn btn-primary" href="{% url 'student:student_edit' student.id %}">Editar</a>
					<a class="btn btn-danger" href="{% url 'student:student_delete' student.id %}">Eliminar</a>
				</td>
			</tr>
			{% endfor %}
			
			
		</tbody>
	</table> 
	<ul class="pager">
		<li>
			{% if page_obj.has_previous %}
	       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
			{% endif %}
	        </li>
		<li>
			{% if page_obj.has_next %}
	     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
	    	{% endif %}
	    </li>
	</ul>

{% else %}
		<h1>No hay registros de estudiantes</h1>
{% endif %}

{% endblock%}

CRUD/templates/student/student_red_average.html
{% extends 'base/base.html' %}

{% block content %}

<h4>Estudiantes con más de un ramo con promedio rojo</h4>

<br>

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for student in object_list %}
		<tr>
			<td>{{ student.id }}</td>
			<td>{{ student.name }}</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de estudiantes</h1>
		{% endif %}
	</tbody>
</table> 
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
{% endblock%}